version: '3.8'

services:
  tearoom:
    build: .
    container_name: tearoom-app
    ports:
      - "9000:9000"
    volumes:
      # Persistent data storage
      - tearoom_data:/app/data
      # Optional: Mount local data for development
      # - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=9000
      - TEAROOM_DATA_PATH=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.tearoom.service=main"
      - "com.tearoom.version=2.0"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: tearoom-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/ssl:ro
    depends_on:
      - tearoom
    restart: unless-stopped
    profiles:
      - production

volumes:
  tearoom_data:
    driver: local
    labels:
      - "com.tearoom.data=persistent"

networks:
  default:
    name: tearoom-network